
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  roles:
    rolenames: ROLE_USER,ROLE_ADMIN
    roledescriptions: User,Admin
  file:
    uploads:
      photos-directory: ./uploads
  security:
    jwt:
      secret: 9db9e39a0dd9c5c2c5b367c6766620a42a9ff9a58f70a5b811601fa0ce9d8780
      expiration: 86400000 # in milliseconds
    mailing:
      frontend:
        sender: contact@app.com
        activation-url: http://localhost:4200/auth/activate
        activation-code-length: 6 # in characters
        activation-code-expiration: 15 # in minutes
        activation-code-characters: 0123456789
        activation-code-subject: Activate your account
    cors:
      origins: http://localhost:4200,http://localhost:8080
server:
  port: 9999
logging:
  level:
    org:
      springframework:
        security: DEBUG
