services:
  mysql:
    image: mysql:9.0.0-oraclelinux9
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DB_NAME}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project-network


  mail-dev:
    image: maildev/maildev
    container_name: maildev_container
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - project-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  project-network:
    driver: bridge